### ISSUE TITLE
 Exception caught by widgets  _TridimensionalDrawerState is a SingleTickerProviderStateMixin but multiple tickers were created.

### ISSUE THREAD

**Issue by devchenli** [CarmineToriello95/tridimensional_drawer#2]
I Navigator to the second page from main page ,The exception occurred when  the keyboard  pops up .

> Excetpion:
> _TridimensionalDrawerState is a SingleTickerProviderStateMixin but multiple tickers were created.
> 
> A SingleTickerProviderStateMixin can only be used as a TickerProvider once.
> 
> If a State is used for multiple AnimationController objects, or if it is passed to other objects and those objects might use it more than one time in total, then instead of mixing in a SingleTickerProviderStateMixin, use a regular TickerProviderStateMixin.

update:
I found  the problem is  :

When you open and close  the drawer quickly, then jump to another page quickly, if the keyboard pops up, the exception occurred...

Is that because the animation is still going on Even though I went to another page，and use another  animation ？

**Comment by CarmineToriello95** [comment]
Hi, thank you so much for reporting this.

I will work on it, recreating the scenario you have described and i will let you know!

**Comment by devchenli** [comment]
Thanks for your reply！here is my exception demo [https://github.com/devchenli/drawer_demo.git](url)
hope you can try it  if you have spare time，
thank you！

**Comment by CarmineToriello95** [comment]
Hey, I have released the version 0.1.0 with the fix for that problem.
Let me know if you still have problems with that. 
Thank you again for your help!

**Comment by devchenli** [comment]
thank you very much , It works well now.
