### ISSUE TITLE
How to figure out the padding?

### ISSUE THREAD

**Issue by StepanMynarik** [CarmineToriello95/tridimensional_drawer#3]
This package looks amazing!

I got it working in no time, but there is one issue. Not all content inside the drawer is visible. It's cut off from the left side, i.e. out of screen.

Is there a way to figure out the horizontal offset reliably on runtime?

Cheers!

**Comment by CarmineToriello95** [comment]
Hi there!

sorry for the late response. Thank you so much for you support and interest!

For the issue you have mentioned, let's say that you set the maxSlide property to 300 and the width of th screen is 500.
This means that, when the drawer is opened, the part of it that is not visible, starting from left, is 200 (width of the screen - maxSlide).
So, at this point, the drawer, from the left side, is 200 not visible and 300 visible.
This means that the content inside the drawer should have a padding left of at least 200.

For calculating the width of the screen you can use: MediaQuery.of(context).size.width.

Let me know if I got your issue and if I was able to help you!

Cheers!

**Comment by StepanMynarik** [comment]
Thank you for the quick answer, that absolutely helped!
