### ISSUE TITLE
The drawer open/close transition is broken on iOS

### ISSUE THREAD

**Issue by StepanMynarik** [CarmineToriello95/tridimensional_drawer#4]
So far I tested this drawer on iOS simulator only. The open/close transition gets stuck half way and looks broken.

Flutter: 0.17.3
Xcode: 11.5
Simulator device: iPhone SE (2nd generation)
iOS: 13.5

**Comment by CarmineToriello95** [comment]
Hey, here I am,

thank you again so much for reporting this.
Does it happen only on the simulator or it happens on the real device too?
